[checker]
cache_file = ".checker."

[[checker.pages]]
name = "example" # required
url = "http://example.com" # required
selector = ""  # CSS Selector
timeout = 10  # second
interval = 600  # second
notify_no_change = true
notify_error = true
notifier = "slack" # slack is only available now

[[checker.pages]]
name = "google"
url = "http://google.com"
selector = ".content"
timeout = 10
interval = 600
notify_no_change = true
notify_error = true
notifier = "slack"

[slack]
webhook_url = "https://hooks.slack.com/services/hogehoge"
channel = ""
username = "checker"
icon_emoji = ""
icon_url = ""
alert_prefix = "<!here> "
